export const userRows = [
  {
    id: 1,
    username: "Andry",
    avatar: "./image/jed6.jpg",
    email: "luc@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 2,
    username: "Jedidya",
    avatar: "./image/jed2.jpg",
    email: "jedidya@gmail.com",
    status: "Active",
    transanction: "R 1000",
  },
  {
    id: 3,
    username: "Kongolo",
    avatar: "./image/jed4.jpg",
    email: "Kongolo@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 4,
    username: "Chris",
    avatar: "./image/jed5.png",
    email: "Chris@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 5,
    username: "Kazadi",
    avatar: "./image/jed3.jpg",
    email: "Chris@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 6,
    username: "Jenovic",
    avatar: "./image/jeje4.png",
    email: "Jenovic@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 7,
    username: "John",
    avatar: "./image/jeje3.png",
    email: "John@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 8,
    username: "Gedeon",
    avatar: "./image/jeje1.png",
    email: "Gedeon@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 9,
    username: "Makamba",
    avatar: "./image/jeje2.png",
    email: "Makamba@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
];
