export const productRows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: "./image/airpords.jpg",
    stock: 45,
    status: "Active",
    price: "R 3200",
  },
  {
    id: 2,
    name: "Iphone",
    img: "./image/iphone.jpg",
    stock: 23,
    status: "Active",
    price: "R 30000",
  },
  {
    id: 3,
    name: "TV",
    img: "./image/tv.jpg",
    stock: 50,
    status: "Active",
    price: "R 18000",
  },
  {
    id: 4,
    name: "Playstation",
    img: "./image/playstation.jpg",
    stock: 100,
    status: "Active",
    price: "R 45000",
  },
  {
    id: 5,
    name: "Shoes",
    img: "./image/shoe.jpg",
    stock: 200,
    status: "Active",
    price: "R 490",
  },
  {
    id: 6,
    name: "Bag",
    img: "./image/bag.jpg",
    stock: 130,
    status: "Active",
    price: "R 700",
  },
  {
    id: 7,
    name: "Belt",
    img: "./image/belt.jpg",
    stock: 50,
    status: "Active",
    price: "R 350",
  },
  {
    id: 8,
    name: "Car",
    img: "./image/car.jpg",
    stock: 10,
    status: "Active",
    price: "R 4000000",
  },
  {
    id: 9,
    name: "Bed",
    img: "./image/bed.jpg",
    stock: 20,
    status: "Active",
    price: "R 4300",
  },
];

export const userRows = [
  {
    id: 1,
    username: "Andry",
    avatar: "./image/jed6.jpg",
    email: "luc@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 2,
    username: "Jedidya",
    avatar: "./image/jed2.jpg",
    email: "jedidya@gmail.com",
    status: "Active",
    transanction: "R 1000",
  },
  {
    id: 3,
    username: "Kongolo",
    avatar: "./image/jed4.jpg",
    email: "Kongolo@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 4,
    username: "Chris",
    avatar: "./image/jed5.png",
    email: "Chris@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 5,
    username: "Kazadi",
    avatar: "./image/jed3.jpg",
    email: "Chris@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 6,
    username: "Jenovic",
    avatar: "./image/jeje4.png",
    email: "Jenovic@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 7,
    username: "John",
    avatar: "./image/jeje3.png",
    email: "John@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 8,
    username: "Gedeon",
    avatar: "./image/jeje1.png",
    email: "Gedeon@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
  {
    id: 9,
    username: "Makamba",
    avatar: "./image/jeje2.png",
    email: "Makamba@gmail.com",
    status: "Active",
    transanction: "R 490",
  },
];
